<?php
Route::get('/', function () { return view('/index'); });
Route::post('/contact/submit', 'Admin\CommentsController@submit');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
Route::post('register', 'Auth\RegisterController@register')->name('auth.register');

Route::group(['middleware' => ['auth', 'approved'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::get('/reports/income', 'Admin\ReportsController@income');
    Route::get('/reports/expenditure', 'Admin\ReportsController@expenditure');
    Route::get('/reports/job-cards', 'Admin\ReportsController@jobCards');
    Route::get('/reports/fuel-purchases', 'Admin\ReportsController@fuelPurchases');
    Route::get('/reports/refunds', 'Admin\ReportsController@refunds');

    
    Route::resource('comments', 'Admin\CommentsController');
    Route::post('comments_mass_destroy', ['uses' => 'Admin\CommentsController@massDestroy', 'as' => 'comments.mass_destroy']);
    Route::post('comments_restore/{id}', ['uses' => 'Admin\CommentsController@restore', 'as' => 'comments.restore']);
    Route::delete('comments_perma_del/{id}', ['uses' => 'Admin\CommentsController@perma_del', 'as' => 'comments.perma_del']);
    Route::resource('departments', 'Admin\DepartmentsController');
    Route::post('departments_mass_destroy', ['uses' => 'Admin\DepartmentsController@massDestroy', 'as' => 'departments.mass_destroy']);
    Route::post('departments_restore/{id}', ['uses' => 'Admin\DepartmentsController@restore', 'as' => 'departments.restore']);
    Route::delete('departments_perma_del/{id}', ['uses' => 'Admin\DepartmentsController@perma_del', 'as' => 'departments.perma_del']);
    Route::resource('employees', 'Admin\EmployeesController');
    Route::post('employees_mass_destroy', ['uses' => 'Admin\EmployeesController@massDestroy', 'as' => 'employees.mass_destroy']);
    Route::post('employees_restore/{id}', ['uses' => 'Admin\EmployeesController@restore', 'as' => 'employees.restore']);
    Route::delete('employees_perma_del/{id}', ['uses' => 'Admin\EmployeesController@perma_del', 'as' => 'employees.perma_del']);
    Route::resource('payee_accounts', 'Admin\PayeeAccountsController');
    Route::post('payee_accounts_mass_destroy', ['uses' => 'Admin\PayeeAccountsController@massDestroy', 'as' => 'payee_accounts.mass_destroy']);
    Route::post('payee_accounts_restore/{id}', ['uses' => 'Admin\PayeeAccountsController@restore', 'as' => 'payee_accounts.restore']);
    Route::delete('payee_accounts_perma_del/{id}', ['uses' => 'Admin\PayeeAccountsController@perma_del', 'as' => 'payee_accounts.perma_del']);
    Route::resource('salaries_request_totals', 'Admin\SalariesRequestTotalsController');
    Route::post('salaries_request_totals_mass_destroy', ['uses' => 'Admin\SalariesRequestTotalsController@massDestroy', 'as' => 'salaries_request_totals.mass_destroy']);
    Route::post('salaries_request_totals_restore/{id}', ['uses' => 'Admin\SalariesRequestTotalsController@restore', 'as' => 'salaries_request_totals.restore']);
    Route::delete('salaries_request_totals_perma_del/{id}', ['uses' => 'Admin\SalariesRequestTotalsController@perma_del', 'as' => 'salaries_request_totals.perma_del']);
    Route::resource('payslips', 'Admin\PayslipsController');
    Route::post('payslips_mass_destroy', ['uses' => 'Admin\PayslipsController@massDestroy', 'as' => 'payslips.mass_destroy']);
    Route::post('payslips_restore/{id}', ['uses' => 'Admin\PayslipsController@restore', 'as' => 'payslips.restore']);
    Route::delete('payslips_perma_del/{id}', ['uses' => 'Admin\PayslipsController@perma_del', 'as' => 'payslips.perma_del']);
    Route::resource('payee_payments', 'Admin\PayeePaymentsController');
    Route::post('payee_payments_mass_destroy', ['uses' => 'Admin\PayeePaymentsController@massDestroy', 'as' => 'payee_payments.mass_destroy']);
    Route::resource('drug_tests', 'Admin\DrugTestsController');
    Route::post('drug_tests_mass_destroy', ['uses' => 'Admin\DrugTestsController@massDestroy', 'as' => 'drug_tests.mass_destroy']);
    Route::post('drug_tests_restore/{id}', ['uses' => 'Admin\DrugTestsController@restore', 'as' => 'drug_tests.restore']);
    Route::delete('drug_tests_perma_del/{id}', ['uses' => 'Admin\DrugTestsController@perma_del', 'as' => 'drug_tests.perma_del']);
    Route::resource('violations', 'Admin\ViolationsController');
    Route::post('violations_mass_destroy', ['uses' => 'Admin\ViolationsController@massDestroy', 'as' => 'violations.mass_destroy']);
    Route::post('violations_restore/{id}', ['uses' => 'Admin\ViolationsController@restore', 'as' => 'violations.restore']);
    Route::delete('violations_perma_del/{id}', ['uses' => 'Admin\ViolationsController@perma_del', 'as' => 'violations.perma_del']);
    Route::resource('vehicles', 'Admin\VehiclesController');
    Route::post('vehicles_mass_destroy', ['uses' => 'Admin\VehiclesController@massDestroy', 'as' => 'vehicles.mass_destroy']);
    Route::post('vehicles_restore/{id}', ['uses' => 'Admin\VehiclesController@restore', 'as' => 'vehicles.restore']);
    Route::delete('vehicles_perma_del/{id}', ['uses' => 'Admin\VehiclesController@perma_del', 'as' => 'vehicles.perma_del']);
    Route::resource('trailers', 'Admin\TrailersController');
    Route::post('trailers_mass_destroy', ['uses' => 'Admin\TrailersController@massDestroy', 'as' => 'trailers.mass_destroy']);
    Route::post('trailers_restore/{id}', ['uses' => 'Admin\TrailersController@restore', 'as' => 'trailers.restore']);
    Route::delete('trailers_perma_del/{id}', ['uses' => 'Admin\TrailersController@perma_del', 'as' => 'trailers.perma_del']);
    Route::resource('light_vehicles', 'Admin\LightVehiclesController');
    Route::post('light_vehicles_mass_destroy', ['uses' => 'Admin\LightVehiclesController@massDestroy', 'as' => 'light_vehicles.mass_destroy']);
    Route::post('light_vehicles_restore/{id}', ['uses' => 'Admin\LightVehiclesController@restore', 'as' => 'light_vehicles.restore']);
    Route::delete('light_vehicles_perma_del/{id}', ['uses' => 'Admin\LightVehiclesController@perma_del', 'as' => 'light_vehicles.perma_del']);
    Route::resource('time_projects', 'Admin\TimeProjectsController');
    Route::post('time_projects_mass_destroy', ['uses' => 'Admin\TimeProjectsController@massDestroy', 'as' => 'time_projects.mass_destroy']);
    Route::resource('quotations', 'Admin\QuotationsController');
    Route::post('quotations_mass_destroy', ['uses' => 'Admin\QuotationsController@massDestroy', 'as' => 'quotations.mass_destroy']);
    Route::resource('income_expense_calculators', 'Admin\IncomeExpenseCalculatorsController');
    Route::post('income_expense_calculators_mass_destroy', ['uses' => 'Admin\IncomeExpenseCalculatorsController@massDestroy', 'as' => 'income_expense_calculators.mass_destroy']);
    Route::post('income_expense_calculators_restore/{id}', ['uses' => 'Admin\IncomeExpenseCalculatorsController@restore', 'as' => 'income_expense_calculators.restore']);
    Route::delete('income_expense_calculators_perma_del/{id}', ['uses' => 'Admin\IncomeExpenseCalculatorsController@perma_del', 'as' => 'income_expense_calculators.perma_del']);
    Route::resource('vendors', 'Admin\VendorsController');
    Route::post('vendors_mass_destroy', ['uses' => 'Admin\VendorsController@massDestroy', 'as' => 'vendors.mass_destroy']);
    Route::post('vendors_restore/{id}', ['uses' => 'Admin\VendorsController@restore', 'as' => 'vendors.restore']);
    Route::delete('vendors_perma_del/{id}', ['uses' => 'Admin\VendorsController@perma_del', 'as' => 'vendors.perma_del']);
    Route::resource('purchase_orders', 'Admin\PurchaseOrdersController');
    Route::post('purchase_orders_mass_destroy', ['uses' => 'Admin\PurchaseOrdersController@massDestroy', 'as' => 'purchase_orders.mass_destroy']);
    Route::resource('road_freight_sub_contractors', 'Admin\RoadFreightSubContractorsController');
    Route::post('road_freight_sub_contractors_mass_destroy', ['uses' => 'Admin\RoadFreightSubContractorsController@massDestroy', 'as' => 'road_freight_sub_contractors.mass_destroy']);
    Route::post('road_freight_sub_contractors_restore/{id}', ['uses' => 'Admin\RoadFreightSubContractorsController@restore', 'as' => 'road_freight_sub_contractors.restore']);
    Route::delete('road_freight_sub_contractors_perma_del/{id}', ['uses' => 'Admin\RoadFreightSubContractorsController@perma_del', 'as' => 'road_freight_sub_contractors.perma_del']);
    Route::resource('vehicle_scs', 'Admin\VehicleScsController');
    Route::post('vehicle_scs_mass_destroy', ['uses' => 'Admin\VehicleScsController@massDestroy', 'as' => 'vehicle_scs.mass_destroy']);
    Route::post('vehicle_scs_restore/{id}', ['uses' => 'Admin\VehicleScsController@restore', 'as' => 'vehicle_scs.restore']);
    Route::delete('vehicle_scs_perma_del/{id}', ['uses' => 'Admin\VehicleScsController@perma_del', 'as' => 'vehicle_scs.perma_del']);
    Route::resource('drivers', 'Admin\DriversController');
    Route::post('drivers_mass_destroy', ['uses' => 'Admin\DriversController@massDestroy', 'as' => 'drivers.mass_destroy']);
    Route::post('drivers_restore/{id}', ['uses' => 'Admin\DriversController@restore', 'as' => 'drivers.restore']);
    Route::delete('drivers_perma_del/{id}', ['uses' => 'Admin\DriversController@perma_del', 'as' => 'drivers.perma_del']);
    Route::resource('time_entries', 'Admin\TimeEntriesController');
    Route::post('time_entries_mass_destroy', ['uses' => 'Admin\TimeEntriesController@massDestroy', 'as' => 'time_entries.mass_destroy']);
    Route::resource('road_freights', 'Admin\RoadFreightsController');
    Route::post('road_freights_mass_destroy', ['uses' => 'Admin\RoadFreightsController@massDestroy', 'as' => 'road_freights.mass_destroy']);
    Route::post('road_freights_restore/{id}', ['uses' => 'Admin\RoadFreightsController@restore', 'as' => 'road_freights.restore']);
    Route::delete('road_freights_perma_del/{id}', ['uses' => 'Admin\RoadFreightsController@perma_del', 'as' => 'road_freights.perma_del']);
    Route::resource('machinery_costs', 'Admin\MachineryCostsController');
    Route::post('machinery_costs_mass_destroy', ['uses' => 'Admin\MachineryCostsController@massDestroy', 'as' => 'machinery_costs.mass_destroy']);
    Route::post('machinery_costs_restore/{id}', ['uses' => 'Admin\MachineryCostsController@restore', 'as' => 'machinery_costs.restore']);
    Route::delete('machinery_costs_perma_del/{id}', ['uses' => 'Admin\MachineryCostsController@perma_del', 'as' => 'machinery_costs.perma_del']);
    Route::resource('fuel_costs', 'Admin\FuelCostsController');
    Route::post('fuel_costs_mass_destroy', ['uses' => 'Admin\FuelCostsController@massDestroy', 'as' => 'fuel_costs.mass_destroy']);
    Route::post('fuel_costs_restore/{id}', ['uses' => 'Admin\FuelCostsController@restore', 'as' => 'fuel_costs.restore']);
    Route::delete('fuel_costs_perma_del/{id}', ['uses' => 'Admin\FuelCostsController@perma_del', 'as' => 'fuel_costs.perma_del']);
    Route::resource('loading_instructions', 'Admin\LoadingInstructionsController');
    Route::post('loading_instructions_mass_destroy', ['uses' => 'Admin\LoadingInstructionsController@massDestroy', 'as' => 'loading_instructions.mass_destroy']);
    Route::post('loading_instructions_restore/{id}', ['uses' => 'Admin\LoadingInstructionsController@restore', 'as' => 'loading_instructions.restore']);
    Route::delete('loading_instructions_perma_del/{id}', ['uses' => 'Admin\LoadingInstructionsController@perma_del', 'as' => 'loading_instructions.perma_del']);
    Route::resource('delivery_instructions', 'Admin\DeliveryInstructionsController');
    Route::post('delivery_instructions_mass_destroy', ['uses' => 'Admin\DeliveryInstructionsController@massDestroy', 'as' => 'delivery_instructions.mass_destroy']);
    Route::post('delivery_instructions_restore/{id}', ['uses' => 'Admin\DeliveryInstructionsController@restore', 'as' => 'delivery_instructions.restore']);
    Route::delete('delivery_instructions_perma_del/{id}', ['uses' => 'Admin\DeliveryInstructionsController@perma_del', 'as' => 'delivery_instructions.perma_del']);
    Route::resource('client_vehicles', 'Admin\ClientVehiclesController');
    Route::post('client_vehicles_mass_destroy', ['uses' => 'Admin\ClientVehiclesController@massDestroy', 'as' => 'client_vehicles.mass_destroy']);
    Route::post('client_vehicles_restore/{id}', ['uses' => 'Admin\ClientVehiclesController@restore', 'as' => 'client_vehicles.restore']);
    Route::delete('client_vehicles_perma_del/{id}', ['uses' => 'Admin\ClientVehiclesController@perma_del', 'as' => 'client_vehicles.perma_del']);
    Route::resource('job_requests', 'Admin\JobRequestsController');
    Route::post('job_requests_mass_destroy', ['uses' => 'Admin\JobRequestsController@massDestroy', 'as' => 'job_requests.mass_destroy']);
    Route::post('job_requests_restore/{id}', ['uses' => 'Admin\JobRequestsController@restore', 'as' => 'job_requests.restore']);
    Route::delete('job_requests_perma_del/{id}', ['uses' => 'Admin\JobRequestsController@perma_del', 'as' => 'job_requests.perma_del']);
    Route::resource('client_job_cards', 'Admin\ClientJobCardsController');
    Route::post('client_job_cards_mass_destroy', ['uses' => 'Admin\ClientJobCardsController@massDestroy', 'as' => 'client_job_cards.mass_destroy']);
    Route::post('client_job_cards_restore/{id}', ['uses' => 'Admin\ClientJobCardsController@restore', 'as' => 'client_job_cards.restore']);
    Route::delete('client_job_cards_perma_del/{id}', ['uses' => 'Admin\ClientJobCardsController@perma_del', 'as' => 'client_job_cards.perma_del']);
    Route::resource('warehouses', 'Admin\WarehousesController');
    Route::post('warehouses_mass_destroy', ['uses' => 'Admin\WarehousesController@massDestroy', 'as' => 'warehouses.mass_destroy']);
    Route::post('warehouses_restore/{id}', ['uses' => 'Admin\WarehousesController@restore', 'as' => 'warehouses.restore']);
    Route::delete('warehouses_perma_del/{id}', ['uses' => 'Admin\WarehousesController@perma_del', 'as' => 'warehouses.perma_del']);
    Route::resource('receivings', 'Admin\ReceivingsController');
    Route::post('receivings_mass_destroy', ['uses' => 'Admin\ReceivingsController@massDestroy', 'as' => 'receivings.mass_destroy']);
    Route::post('receivings_restore/{id}', ['uses' => 'Admin\ReceivingsController@restore', 'as' => 'receivings.restore']);
    Route::delete('receivings_perma_del/{id}', ['uses' => 'Admin\ReceivingsController@perma_del', 'as' => 'receivings.perma_del']);
    Route::resource('releasings', 'Admin\ReleasingsController');
    Route::post('releasings_mass_destroy', ['uses' => 'Admin\ReleasingsController@massDestroy', 'as' => 'releasings.mass_destroy']);
    Route::post('releasings_restore/{id}', ['uses' => 'Admin\ReleasingsController@restore', 'as' => 'releasings.restore']);
    Route::delete('releasings_perma_del/{id}', ['uses' => 'Admin\ReleasingsController@perma_del', 'as' => 'releasings.perma_del']);
    Route::resource('clearance_and_forwardings', 'Admin\ClearanceAndForwardingsController');
    Route::post('clearance_and_forwardings_mass_destroy', ['uses' => 'Admin\ClearanceAndForwardingsController@massDestroy', 'as' => 'clearance_and_forwardings.mass_destroy']);
    Route::post('clearance_and_forwardings_restore/{id}', ['uses' => 'Admin\ClearanceAndForwardingsController@restore', 'as' => 'clearance_and_forwardings.restore']);
    Route::delete('clearance_and_forwardings_perma_del/{id}', ['uses' => 'Admin\ClearanceAndForwardingsController@perma_del', 'as' => 'clearance_and_forwardings.perma_del']);
    Route::resource('air_freights', 'Admin\AirFreightsController');
    Route::post('air_freights_mass_destroy', ['uses' => 'Admin\AirFreightsController@massDestroy', 'as' => 'air_freights.mass_destroy']);
    Route::post('air_freights_restore/{id}', ['uses' => 'Admin\AirFreightsController@restore', 'as' => 'air_freights.restore']);
    Route::delete('air_freights_perma_del/{id}', ['uses' => 'Admin\AirFreightsController@perma_del', 'as' => 'air_freights.perma_del']);
    Route::resource('rail_freights', 'Admin\RailFreightsController');
    Route::post('rail_freights_mass_destroy', ['uses' => 'Admin\RailFreightsController@massDestroy', 'as' => 'rail_freights.mass_destroy']);
    Route::post('rail_freights_restore/{id}', ['uses' => 'Admin\RailFreightsController@restore', 'as' => 'rail_freights.restore']);
    Route::delete('rail_freights_perma_del/{id}', ['uses' => 'Admin\RailFreightsController@perma_del', 'as' => 'rail_freights.perma_del']);
    Route::resource('sea_freights', 'Admin\SeaFreightsController');
    Route::post('sea_freights_mass_destroy', ['uses' => 'Admin\SeaFreightsController@massDestroy', 'as' => 'sea_freights.mass_destroy']);
    Route::post('sea_freights_restore/{id}', ['uses' => 'Admin\SeaFreightsController@restore', 'as' => 'sea_freights.restore']);
    Route::delete('sea_freights_perma_del/{id}', ['uses' => 'Admin\SeaFreightsController@perma_del', 'as' => 'sea_freights.perma_del']);
    Route::resource('time_reports', 'Admin\TimeReportsController');
    Route::resource('workshops', 'Admin\WorkshopsController');
    Route::post('workshops_mass_destroy', ['uses' => 'Admin\WorkshopsController@massDestroy', 'as' => 'workshops.mass_destroy']);
    Route::post('workshops_restore/{id}', ['uses' => 'Admin\WorkshopsController@restore', 'as' => 'workshops.restore']);
    Route::delete('workshops_perma_del/{id}', ['uses' => 'Admin\WorkshopsController@perma_del', 'as' => 'workshops.perma_del']);
    Route::resource('parts', 'Admin\PartsController');
    Route::post('parts_mass_destroy', ['uses' => 'Admin\PartsController@massDestroy', 'as' => 'parts.mass_destroy']);
    Route::post('parts_restore/{id}', ['uses' => 'Admin\PartsController@restore', 'as' => 'parts.restore']);
    Route::delete('parts_perma_del/{id}', ['uses' => 'Admin\PartsController@perma_del', 'as' => 'parts.perma_del']);
    Route::resource('parts_acquireds', 'Admin\PartsAcquiredsController');
    Route::post('parts_acquireds_mass_destroy', ['uses' => 'Admin\PartsAcquiredsController@massDestroy', 'as' => 'parts_acquireds.mass_destroy']);
    Route::post('parts_acquireds_restore/{id}', ['uses' => 'Admin\PartsAcquiredsController@restore', 'as' => 'parts_acquireds.restore']);
    Route::delete('parts_acquireds_perma_del/{id}', ['uses' => 'Admin\PartsAcquiredsController@perma_del', 'as' => 'parts_acquireds.perma_del']);
    Route::resource('client_accounts', 'Admin\ClientAccountsController');
    Route::post('client_accounts_mass_destroy', ['uses' => 'Admin\ClientAccountsController@massDestroy', 'as' => 'client_accounts.mass_destroy']);
    Route::post('client_accounts_restore/{id}', ['uses' => 'Admin\ClientAccountsController@restore', 'as' => 'client_accounts.restore']);
    Route::delete('client_accounts_perma_del/{id}', ['uses' => 'Admin\ClientAccountsController@perma_del', 'as' => 'client_accounts.perma_del']);
    Route::resource('income_categories', 'Admin\IncomeCategoriesController');
    Route::post('income_categories_mass_destroy', ['uses' => 'Admin\IncomeCategoriesController@massDestroy', 'as' => 'income_categories.mass_destroy']);
    Route::resource('credit_notes', 'Admin\CreditNotesController');
    Route::post('credit_notes_mass_destroy', ['uses' => 'Admin\CreditNotesController@massDestroy', 'as' => 'credit_notes.mass_destroy']);
    Route::resource('vendor_accounts', 'Admin\VendorAccountsController');
    Route::post('vendor_accounts_mass_destroy', ['uses' => 'Admin\VendorAccountsController@massDestroy', 'as' => 'vendor_accounts.mass_destroy']);
    Route::post('vendor_accounts_restore/{id}', ['uses' => 'Admin\VendorAccountsController@restore', 'as' => 'vendor_accounts.restore']);
    Route::delete('vendor_accounts_perma_del/{id}', ['uses' => 'Admin\VendorAccountsController@perma_del', 'as' => 'vendor_accounts.perma_del']);
    Route::resource('expense_categories', 'Admin\ExpenseCategoriesController');
    Route::post('expense_categories_mass_destroy', ['uses' => 'Admin\ExpenseCategoriesController@massDestroy', 'as' => 'expense_categories.mass_destroy']);
    Route::resource('debit_notes', 'Admin\DebitNotesController');
    Route::post('debit_notes_mass_destroy', ['uses' => 'Admin\DebitNotesController@massDestroy', 'as' => 'debit_notes.mass_destroy']);
    Route::resource('bank_payments', 'Admin\BankPaymentsController');
    Route::post('bank_payments_mass_destroy', ['uses' => 'Admin\BankPaymentsController@massDestroy', 'as' => 'bank_payments.mass_destroy']);
    Route::resource('incomes', 'Admin\IncomesController');
    Route::post('incomes_mass_destroy', ['uses' => 'Admin\IncomesController@massDestroy', 'as' => 'incomes.mass_destroy']);
    Route::resource('vendor_bank_payments', 'Admin\VendorBankPaymentsController');
    Route::post('vendor_bank_payments_mass_destroy', ['uses' => 'Admin\VendorBankPaymentsController@massDestroy', 'as' => 'vendor_bank_payments.mass_destroy']);
    Route::resource('expenses', 'Admin\ExpensesController');
    Route::post('expenses_mass_destroy', ['uses' => 'Admin\ExpensesController@massDestroy', 'as' => 'expenses.mass_destroy']);
    Route::resource('monthly_reports', 'Admin\MonthlyReportsController');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('user_actions', 'Admin\UserActionsController');
    Route::resource('routes', 'Admin\RoutesController');
    Route::post('routes_mass_destroy', ['uses' => 'Admin\RoutesController@massDestroy', 'as' => 'routes.mass_destroy']);
    Route::post('routes_restore/{id}', ['uses' => 'Admin\RoutesController@restore', 'as' => 'routes.restore']);
    Route::delete('routes_perma_del/{id}', ['uses' => 'Admin\RoutesController@perma_del', 'as' => 'routes.perma_del']);
    Route::resource('operation_types', 'Admin\OperationTypesController');
    Route::post('operation_types_mass_destroy', ['uses' => 'Admin\OperationTypesController@massDestroy', 'as' => 'operation_types.mass_destroy']);
    Route::post('operation_types_restore/{id}', ['uses' => 'Admin\OperationTypesController@restore', 'as' => 'operation_types.restore']);
    Route::delete('operation_types_perma_del/{id}', ['uses' => 'Admin\OperationTypesController@perma_del', 'as' => 'operation_types.perma_del']);
    Route::resource('time_work_types', 'Admin\TimeWorkTypesController');
    Route::post('time_work_types_mass_destroy', ['uses' => 'Admin\TimeWorkTypesController@massDestroy', 'as' => 'time_work_types.mass_destroy']);
    Route::resource('truck_attachment_statuses', 'Admin\TruckAttachmentStatusesController');
    Route::post('truck_attachment_statuses_mass_destroy', ['uses' => 'Admin\TruckAttachmentStatusesController@massDestroy', 'as' => 'truck_attachment_statuses.mass_destroy']);
    Route::post('truck_attachment_statuses_restore/{id}', ['uses' => 'Admin\TruckAttachmentStatusesController@restore', 'as' => 'truck_attachment_statuses.restore']);
    Route::delete('truck_attachment_statuses_perma_del/{id}', ['uses' => 'Admin\TruckAttachmentStatusesController@perma_del', 'as' => 'truck_attachment_statuses.perma_del']);
    Route::resource('machinery_types', 'Admin\MachineryTypesController');
    Route::post('machinery_types_mass_destroy', ['uses' => 'Admin\MachineryTypesController@massDestroy', 'as' => 'machinery_types.mass_destroy']);
    Route::post('machinery_types_restore/{id}', ['uses' => 'Admin\MachineryTypesController@restore', 'as' => 'machinery_types.restore']);
    Route::delete('machinery_types_perma_del/{id}', ['uses' => 'Admin\MachineryTypesController@perma_del', 'as' => 'machinery_types.perma_del']);
    Route::resource('machinery_sizes', 'Admin\MachinerySizesController');
    Route::post('machinery_sizes_mass_destroy', ['uses' => 'Admin\MachinerySizesController@massDestroy', 'as' => 'machinery_sizes.mass_destroy']);
    Route::post('machinery_sizes_restore/{id}', ['uses' => 'Admin\MachinerySizesController@restore', 'as' => 'machinery_sizes.restore']);
    Route::delete('machinery_sizes_perma_del/{id}', ['uses' => 'Admin\MachinerySizesController@perma_del', 'as' => 'machinery_sizes.perma_del']);
    Route::resource('invoice_items', 'Admin\InvoiceItemsController');
    Route::post('invoice_items_mass_destroy', ['uses' => 'Admin\InvoiceItemsController@massDestroy', 'as' => 'invoice_items.mass_destroy']);
    Route::post('invoice_items_restore/{id}', ['uses' => 'Admin\InvoiceItemsController@restore', 'as' => 'invoice_items.restore']);
    Route::delete('invoice_items_perma_del/{id}', ['uses' => 'Admin\InvoiceItemsController@perma_del', 'as' => 'invoice_items.perma_del']);
    Route::resource('load_descriptions', 'Admin\LoadDescriptionsController');
    Route::post('load_descriptions_mass_destroy', ['uses' => 'Admin\LoadDescriptionsController@massDestroy', 'as' => 'load_descriptions.mass_destroy']);
    Route::post('load_descriptions_restore/{id}', ['uses' => 'Admin\LoadDescriptionsController@restore', 'as' => 'load_descriptions.restore']);
    Route::delete('load_descriptions_perma_del/{id}', ['uses' => 'Admin\LoadDescriptionsController@perma_del', 'as' => 'load_descriptions.perma_del']);
    Route::resource('overtime_and_bonus_items', 'Admin\OvertimeAndBonusItemsController');
    Route::post('overtime_and_bonus_items_mass_destroy', ['uses' => 'Admin\OvertimeAndBonusItemsController@massDestroy', 'as' => 'overtime_and_bonus_items.mass_destroy']);
    Route::post('overtime_and_bonus_items_restore/{id}', ['uses' => 'Admin\OvertimeAndBonusItemsController@restore', 'as' => 'overtime_and_bonus_items.restore']);
    Route::delete('overtime_and_bonus_items_perma_del/{id}', ['uses' => 'Admin\OvertimeAndBonusItemsController@perma_del', 'as' => 'overtime_and_bonus_items.perma_del']);
    Route::resource('deduction_items', 'Admin\DeductionItemsController');
    Route::post('deduction_items_mass_destroy', ['uses' => 'Admin\DeductionItemsController@massDestroy', 'as' => 'deduction_items.mass_destroy']);
    Route::post('deduction_items_restore/{id}', ['uses' => 'Admin\DeductionItemsController@restore', 'as' => 'deduction_items.restore']);
    Route::delete('deduction_items_perma_del/{id}', ['uses' => 'Admin\DeductionItemsController@perma_del', 'as' => 'deduction_items.perma_del']);
    Route::resource('job_card_items', 'Admin\JobCardItemsController');
    Route::post('job_card_items_mass_destroy', ['uses' => 'Admin\JobCardItemsController@massDestroy', 'as' => 'job_card_items.mass_destroy']);
    Route::post('job_card_items_restore/{id}', ['uses' => 'Admin\JobCardItemsController@restore', 'as' => 'job_card_items.restore']);
    Route::delete('job_card_items_perma_del/{id}', ['uses' => 'Admin\JobCardItemsController@perma_del', 'as' => 'job_card_items.perma_del']);
    Route::resource('loading_requirements', 'Admin\LoadingRequirementsController');
    Route::post('loading_requirements_mass_destroy', ['uses' => 'Admin\LoadingRequirementsController@massDestroy', 'as' => 'loading_requirements.mass_destroy']);
    Route::post('loading_requirements_restore/{id}', ['uses' => 'Admin\LoadingRequirementsController@restore', 'as' => 'loading_requirements.restore']);
    Route::delete('loading_requirements_perma_del/{id}', ['uses' => 'Admin\LoadingRequirementsController@perma_del', 'as' => 'loading_requirements.perma_del']);
    Route::resource('received_items', 'Admin\ReceivedItemsController');
    Route::post('received_items_mass_destroy', ['uses' => 'Admin\ReceivedItemsController@massDestroy', 'as' => 'received_items.mass_destroy']);
    Route::post('received_items_restore/{id}', ['uses' => 'Admin\ReceivedItemsController@restore', 'as' => 'received_items.restore']);
    Route::delete('received_items_perma_del/{id}', ['uses' => 'Admin\ReceivedItemsController@perma_del', 'as' => 'received_items.perma_del']);
    Route::resource('qualifications', 'Admin\QualificationsController');
    Route::post('qualifications_mass_destroy', ['uses' => 'Admin\QualificationsController@massDestroy', 'as' => 'qualifications.mass_destroy']);
    Route::post('qualifications_restore/{id}', ['uses' => 'Admin\QualificationsController@restore', 'as' => 'qualifications.restore']);
    Route::delete('qualifications_perma_del/{id}', ['uses' => 'Admin\QualificationsController@perma_del', 'as' => 'qualifications.perma_del']);
    Route::resource('emergency_contacts', 'Admin\EmergencyContactsController');
    Route::post('emergency_contacts_mass_destroy', ['uses' => 'Admin\EmergencyContactsController@massDestroy', 'as' => 'emergency_contacts.mass_destroy']);
    Route::post('emergency_contacts_restore/{id}', ['uses' => 'Admin\EmergencyContactsController@restore', 'as' => 'emergency_contacts.restore']);
    Route::delete('emergency_contacts_perma_del/{id}', ['uses' => 'Admin\EmergencyContactsController@perma_del', 'as' => 'emergency_contacts.perma_del']);
    Route::resource('beneficiary_details', 'Admin\BeneficiaryDetailsController');
    Route::post('beneficiary_details_mass_destroy', ['uses' => 'Admin\BeneficiaryDetailsController@massDestroy', 'as' => 'beneficiary_details.mass_destroy']);
    Route::post('beneficiary_details_restore/{id}', ['uses' => 'Admin\BeneficiaryDetailsController@restore', 'as' => 'beneficiary_details.restore']);
    Route::delete('beneficiary_details_perma_del/{id}', ['uses' => 'Admin\BeneficiaryDetailsController@perma_del', 'as' => 'beneficiary_details.perma_del']);
    Route::resource('identifications', 'Admin\IdentificationsController');
    Route::post('identifications_mass_destroy', ['uses' => 'Admin\IdentificationsController@massDestroy', 'as' => 'identifications.mass_destroy']);
    Route::post('identifications_restore/{id}', ['uses' => 'Admin\IdentificationsController@restore', 'as' => 'identifications.restore']);
    Route::delete('identifications_perma_del/{id}', ['uses' => 'Admin\IdentificationsController@perma_del', 'as' => 'identifications.perma_del']);
    Route::resource('non_machine_costs', 'Admin\NonMachineCostsController');
    Route::post('non_machine_costs_mass_destroy', ['uses' => 'Admin\NonMachineCostsController@massDestroy', 'as' => 'non_machine_costs.mass_destroy']);
    Route::post('non_machine_costs_restore/{id}', ['uses' => 'Admin\NonMachineCostsController@restore', 'as' => 'non_machine_costs.restore']);
    Route::delete('non_machine_costs_perma_del/{id}', ['uses' => 'Admin\NonMachineCostsController@perma_del', 'as' => 'non_machine_costs.perma_del']);
    Route::resource('client_contacts', 'Admin\ClientContactsController');
    Route::post('client_contacts_mass_destroy', ['uses' => 'Admin\ClientContactsController@massDestroy', 'as' => 'client_contacts.mass_destroy']);
    Route::post('client_contacts_restore/{id}', ['uses' => 'Admin\ClientContactsController@restore', 'as' => 'client_contacts.restore']);
    Route::delete('client_contacts_perma_del/{id}', ['uses' => 'Admin\ClientContactsController@perma_del', 'as' => 'client_contacts.perma_del']);
    Route::resource('vendor_contacts', 'Admin\VendorContactsController');
    Route::post('vendor_contacts_mass_destroy', ['uses' => 'Admin\VendorContactsController@massDestroy', 'as' => 'vendor_contacts.mass_destroy']);
    Route::post('vendor_contacts_restore/{id}', ['uses' => 'Admin\VendorContactsController@restore', 'as' => 'vendor_contacts.restore']);
    Route::delete('vendor_contacts_perma_del/{id}', ['uses' => 'Admin\VendorContactsController@perma_del', 'as' => 'vendor_contacts.perma_del']);
    Route::resource('currencies', 'Admin\CurrenciesController');
    Route::post('currencies_mass_destroy', ['uses' => 'Admin\CurrenciesController@massDestroy', 'as' => 'currencies.mass_destroy']);
    Route::post('currencies_restore/{id}', ['uses' => 'Admin\CurrenciesController@restore', 'as' => 'currencies.restore']);
    Route::delete('currencies_perma_del/{id}', ['uses' => 'Admin\CurrenciesController@perma_del', 'as' => 'currencies.perma_del']);
    Route::resource('inhouse_job_cards', 'Admin\InhouseJobCardsController');
    Route::post('inhouse_job_cards_mass_destroy', ['uses' => 'Admin\InhouseJobCardsController@massDestroy', 'as' => 'inhouse_job_cards.mass_destroy']);
    Route::post('inhouse_job_cards_restore/{id}', ['uses' => 'Admin\InhouseJobCardsController@restore', 'as' => 'inhouse_job_cards.restore']);
    Route::delete('inhouse_job_cards_perma_del/{id}', ['uses' => 'Admin\InhouseJobCardsController@perma_del', 'as' => 'inhouse_job_cards.perma_del']);
    Route::resource('unit_measurements', 'Admin\UnitMeasurementsController');
    Route::post('unit_measurements_mass_destroy', ['uses' => 'Admin\UnitMeasurementsController@massDestroy', 'as' => 'unit_measurements.mass_destroy']);
    Route::post('unit_measurements_restore/{id}', ['uses' => 'Admin\UnitMeasurementsController@restore', 'as' => 'unit_measurements.restore']);
    Route::delete('unit_measurements_perma_del/{id}', ['uses' => 'Admin\UnitMeasurementsController@perma_del', 'as' => 'unit_measurements.perma_del']);
    Route::resource('schedule_of_services', 'Admin\ScheduleOfServicesController');
    Route::post('schedule_of_services_mass_destroy', ['uses' => 'Admin\ScheduleOfServicesController@massDestroy', 'as' => 'schedule_of_services.mass_destroy']);
    Route::post('schedule_of_services_restore/{id}', ['uses' => 'Admin\ScheduleOfServicesController@restore', 'as' => 'schedule_of_services.restore']);
    Route::delete('schedule_of_services_perma_del/{id}', ['uses' => 'Admin\ScheduleOfServicesController@perma_del', 'as' => 'schedule_of_services.perma_del']);
    Route::get('internal_notifications/read', 'Admin\InternalNotificationsController@read');
    Route::resource('internal_notifications', 'Admin\InternalNotificationsController');
    Route::post('internal_notifications_mass_destroy', ['uses' => 'Admin\InternalNotificationsController@massDestroy', 'as' => 'internal_notifications.mass_destroy']);
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');

    Route::model('messenger', 'App\MessengerTopic');
    Route::get('messenger/inbox', 'Admin\MessengerController@inbox')->name('messenger.inbox');
    Route::get('messenger/outbox', 'Admin\MessengerController@outbox')->name('messenger.outbox');
    Route::resource('messenger', 'Admin\MessengerController');

    Route::get('quotations/{quotation_id}/download', 'Admin\QuotationsController@download')->name('quotations.download');
    Route::get('purchase_orders/{purchase_order_id}/download', 'Admin\PurchaseOrdersController@download')->name('purchase_orders.download');
    Route::get('client_accounts/{client_account_id}/download', 'Admin\ClientAccountsController@download')->name('client_accounts.download');
    Route::get('vendor_accounts/{vendor_account_id}/download', 'Admin\VendorAccountsController@download')->name('vendor_accounts.download');
    Route::get('debit_notes/{debit_note_id}/download', 'Admin\DebitNotesController@download')->name('debit_notes.download');
    Route::get('credit_notes/{credit_note_id}/download', 'Admin\CreditNotesController@download')->name('credit_notes.download');
    Route::get('income_categories/{income_category_id}/download', 'Admin\IncomeCategoriesController@download')->name('income_categories.download');
    Route::get('expense_categories/{expense_category_id}/download', 'Admin\ExpenseCategoriesController@download')->name('expense_categories.download');
    Route::get('road_freights/{road_freight_id}/download', 'Admin\RoadFreightsController@download')->name('road_freights.download');
    Route::get('loading_instructions/{load_instruction_id}/download', 'Admin\LoadingInstructionsController@download')->name('loading_instructions.download');
    Route::get('delivery-instructions/{delivery-instruction_id}/download', 'Admin\DeliveryInstructionsController@download')->name('delivery_instructions.download');
    Route::get('receivings/{receiving_id}/download', 'Admin\ReceivingsController@download')->name('receivings.download');
    Route::get('releasings/{releasing_id}/download', 'Admin\ReleasingsController@download')->name('releasings.download');
    Route::get('inhouse_job_cards/{inhouse_job_card_id}/download', 'Admin\InhouseJobCardsController@download')->name('inhouse_job_cards.download');
    Route::get('client_job_cards/{client_job_card_id}/download', 'Admin\ClientJobCardsController@download')->name('client_job_cards.download');
    Route::get('workshops/{workshop_id}/download', 'Admin\WorkshopsController@download')->name('workshops.download');
    Route::get('warehouses/{warehouse_id}/download', 'Admin\WarehousesController@download')->name('warehouses.download');
    Route::get('payslips/{payslip_id}/download', 'Admin\PayslipsController@download')->name('payslips.download');
    Route::get('clearance_and_forwardings/{clearance_and_forwarding_id}/download', 'Admin\ClearanceAndForwardingsController@download')->name('clearance_and_forwardings.download');
    Route::get('air_freights/{air_freight_id}/download', 'Admin\AirFreightsController@download')->name('air_freights.download');
    Route::get('rail_freights/{rail_freight_id}/download', 'Admin\RailFreightsController@download')->name('rail_freights.download');
    Route::get('sea_freights/{sea_freight_id}/download', 'Admin\SeaFreightsController@download')->name('sea_freights.download');
    Route::get('time_projects/{time_project_id}/download', 'Admin\TimeProjectsController@download')->name('time_projects.download');
 
});
